// <auto-generated />
using System;
using FamilyVault.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyVault.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20251225075441_MigrationV1")]
partial class MigrationV1
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("FamilyVault.Domain.Entities.DocumentDetails", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("DocumentNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DocumentType")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("ExpiryDate")
                    .HasColumnType("datetime2");

                b.Property<Guid>("FamilyMemberId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<DateTime>("IssueDate")
                    .HasColumnType("datetime2");

                b.Property<string>("SavedLocation")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("FamilyMemberId");

                b.ToTable("Documents");
            });

        modelBuilder.Entity("FamilyVault.Domain.Entities.Family", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Families");
            });

        modelBuilder.Entity("FamilyVault.Domain.Entities.FamilyMember", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<long?>("Aadhar")
                    .HasMaxLength(12)
                    .HasColumnType("bigint");

                b.Property<int?>("BloodGroup")
                    .HasColumnType("int");

                b.Property<string>("CountryCode")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTimeOffset?>("DateOfBirth")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("FamilyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("LastName")
                    .HasColumnType("nvarchar(max)");

                b.Property<long?>("Mobile")
                    .HasMaxLength(10)
                    .HasColumnType("bigint");

                b.Property<long?>("PAN")
                    .HasMaxLength(10)
                    .HasColumnType("bigint");

                b.Property<int>("RelationshipType")
                    .HasColumnType("int");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("FamilyId");

                b.ToTable("FamilyMembers");
            });

        modelBuilder.Entity("FamilyVault.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CountryCode")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("LastName")
                    .HasColumnType("nvarchar(max)");

                b.Property<long?>("Mobile")
                    .HasMaxLength(10)
                    .HasColumnType("bigint");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Users");
            });

        modelBuilder.Entity("FamilyVault.Domain.Entities.DocumentDetails", b =>
            {
                b.HasOne("FamilyVault.Domain.Entities.FamilyMember", "FamilyMember")
                    .WithMany()
                    .HasForeignKey("FamilyMemberId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("FamilyMember");
            });

        modelBuilder.Entity("FamilyVault.Domain.Entities.Family", b =>
            {
                b.HasOne("FamilyVault.Domain.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("FamilyVault.Domain.Entities.FamilyMember", b =>
            {
                b.HasOne("FamilyVault.Domain.Entities.Family", "Family")
                    .WithMany()
                    .HasForeignKey("FamilyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Family");
            });
#pragma warning restore 612, 618
    }
}
